/**
 * FitCommit Trusted Nutrition Database
 * Curated from USDA FoodData Central (FDC) and Indian Food Composition Tables (IFCT / ICMR).
 * All macro and energy values are strictly per 100 grams of edible portion.
 */

const NUTRITION_DATABASE = [
  // -------------------------------------------------------------
  // 1. RICE & GRAINS
  // -------------------------------------------------------------
  {
    id: 'usda_rice_white_cooked',
    name: 'White Rice',
    aliases: ['rice', 'white rice', 'cooked white rice', 'steamed rice', 'basmati rice', 'boiled rice', 'plain rice', 'chawal'],
    category: 'Grains & Cereals',
    serving_size_g: 100,
    calories: 130,
    protein_g: 2.7,
    carbs_g: 28.2,
    fat_g: 0.3,
    fiber_g: 0.4,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169756'
  },
  {
    id: 'usda_rice_brown_cooked',
    name: 'Brown Rice',
    aliases: ['brown rice', 'cooked brown rice', 'steamed brown rice', 'whole grain rice'],
    category: 'Grains & Cereals',
    serving_size_g: 100,
    calories: 111,
    protein_g: 2.6,
    carbs_g: 23.0,
    fat_g: 0.9,
    fiber_g: 1.8,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169704'
  },
  {
    id: 'usda_oats_cooked',
    name: 'Oatmeal / Cooked Oats',
    aliases: ['oats', 'oatmeal', 'porridge', 'rolled oats', 'steel cut oats', 'cooked oats'],
    category: 'Grains & Cereals',
    serving_size_g: 100,
    calories: 71,
    protein_g: 2.5,
    carbs_g: 12.0,
    fat_g: 1.5,
    fiber_g: 1.7,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173904'
  },
  {
    id: 'usda_quinoa_cooked',
    name: 'Cooked Quinoa',
    aliases: ['quinoa', 'cooked quinoa', 'herbed quinoa'],
    category: 'Grains & Cereals',
    serving_size_g: 100,
    calories: 120,
    protein_g: 4.4,
    carbs_g: 21.3,
    fat_g: 1.9,
    fiber_g: 2.8,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 168917'
  },
  {
    id: 'usda_bread_toast',
    name: 'Whole Wheat Toast / Bread',
    aliases: ['toast', 'bread', 'whole wheat bread', 'wheat toast', 'brown bread', 'toasted bread', 'white bread', 'slice of bread'],
    category: 'Grains & Cereals',
    serving_size_g: 100,
    calories: 247,
    protein_g: 12.0,
    carbs_g: 41.3,
    fat_g: 3.4,
    fiber_g: 6.0,
    preparation: 'baked',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 172685'
  },

  // -------------------------------------------------------------
  // 2. INDIAN BREADS & ROTIS
  // -------------------------------------------------------------
  {
    id: 'ifct_roti_chapati',
    name: 'Chapati / Roti',
    aliases: ['chapati', 'roti', 'wheat chapati', 'phulka', 'whole wheat roti', 'plain roti', 'fulka'],
    category: 'Indian Breads',
    serving_size_g: 100,
    calories: 250,
    protein_g: 8.5,
    carbs_g: 50.0,
    fat_g: 2.5,
    fiber_g: 6.5,
    preparation: 'roasted',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: C002'
  },
  {
    id: 'ifct_naan_bread',
    name: 'Naan',
    aliases: ['naan', 'plain naan', 'tandoori naan', 'garlic naan', 'butter naan'],
    category: 'Indian Breads',
    serving_size_g: 100,
    calories: 290,
    protein_g: 8.0,
    carbs_g: 52.0,
    fat_g: 6.0,
    fiber_g: 2.2,
    preparation: 'baked',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: C005'
  },
  {
    id: 'ifct_paratha_plain',
    name: 'Paratha',
    aliases: ['paratha', 'plain paratha', 'tawa paratha', 'laccha paratha', 'aloo paratha'],
    category: 'Indian Breads',
    serving_size_g: 100,
    calories: 325,
    protein_g: 6.8,
    carbs_g: 46.0,
    fat_g: 13.0,
    fiber_g: 4.2,
    preparation: 'fried',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: C008'
  },

  // -------------------------------------------------------------
  // 3. SOUTH INDIAN DISHES
  // -------------------------------------------------------------
  {
    id: 'ifct_idli_steamed',
    name: 'Idli',
    aliases: ['idli', 'steamed idli', 'rice idli', 'idlis'],
    category: 'South Indian Breakfast',
    serving_size_g: 100,
    calories: 136,
    protein_g: 4.2,
    carbs_g: 28.5,
    fat_g: 0.5,
    fiber_g: 1.5,
    preparation: 'steamed',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: SI01'
  },
  {
    id: 'ifct_dosa_plain',
    name: 'Plain Dosa',
    aliases: ['dosa', 'plain dosa', 'sada dosa', 'crispy dosa', 'dosai'],
    category: 'South Indian Breakfast',
    serving_size_g: 100,
    calories: 168,
    protein_g: 3.9,
    carbs_g: 29.0,
    fat_g: 3.7,
    fiber_g: 1.2,
    preparation: 'fried',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: SI03'
  },
  {
    id: 'ifct_masala_dosa',
    name: 'Masala Dosa',
    aliases: ['masala dosa', 'aloo masala dosa', 'potato masala dosa'],
    category: 'South Indian Breakfast',
    serving_size_g: 100,
    calories: 205,
    protein_g: 4.4,
    carbs_g: 32.0,
    fat_g: 6.8,
    fiber_g: 2.1,
    preparation: 'fried',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: SI04'
  },
  {
    id: 'ifct_medu_vada',
    name: 'Medu Vada',
    aliases: ['vada', 'medu vada', 'urad vada', 'vadai'],
    category: 'South Indian Breakfast',
    serving_size_g: 100,
    calories: 260,
    protein_g: 8.2,
    carbs_g: 26.5,
    fat_g: 14.0,
    fiber_g: 3.5,
    preparation: 'deep_fried',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: SI06'
  },
  {
    id: 'ifct_sambar_vegetable',
    name: 'Sambar',
    aliases: ['sambar', 'vegetable sambar', 'south indian sambar'],
    category: 'Lentils & Soups',
    serving_size_g: 100,
    calories: 62,
    protein_g: 2.8,
    carbs_g: 9.5,
    fat_g: 1.5,
    fiber_g: 2.4,
    preparation: 'boiled',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: SI08'
  },
  {
    id: 'ifct_poha_cooked',
    name: 'Poha',
    aliases: ['poha', 'kanda poha', 'flattened rice', 'chivda cooked', 'batata poha'],
    category: 'Indian Breakfast',
    serving_size_g: 100,
    calories: 165,
    protein_g: 3.2,
    carbs_g: 27.0,
    fat_g: 4.8,
    fiber_g: 1.9,
    preparation: 'cooked',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: B012'
  },
  {
    id: 'ifct_upma_cooked',
    name: 'Upma',
    aliases: ['upma', 'rava upma', 'sooji upma', 'semolina upma'],
    category: 'Indian Breakfast',
    serving_size_g: 100,
    calories: 155,
    protein_g: 3.8,
    carbs_g: 25.5,
    fat_g: 4.5,
    fiber_g: 1.6,
    preparation: 'cooked',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: B015'
  },

  // -------------------------------------------------------------
  // 4. DALS & PULSES
  // -------------------------------------------------------------
  {
    id: 'ifct_dal_tadka',
    name: 'Yellow Dal / Dal Tadka',
    aliases: ['dal', 'yellow dal', 'dal tadka', 'dal fry', 'toor dal', 'moong dal', 'cooked dal', 'lentil curry'],
    category: 'Legumes & Pulses',
    serving_size_g: 100,
    calories: 105,
    protein_g: 6.5,
    carbs_g: 14.5,
    fat_g: 2.5,
    fiber_g: 3.8,
    preparation: 'curry',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: P004'
  },
  {
    id: 'ifct_rajma_curry',
    name: 'Rajma / Kidney Bean Curry',
    aliases: ['rajma', 'rajma masala', 'kidney beans curry', 'cooked rajma'],
    category: 'Legumes & Pulses',
    serving_size_g: 100,
    calories: 135,
    protein_g: 7.8,
    carbs_g: 19.5,
    fat_g: 3.2,
    fiber_g: 5.5,
    preparation: 'curry',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: P012'
  },
  {
    id: 'ifct_chole_chana_masala',
    name: 'Chole / Chana Masala',
    aliases: ['chole', 'chana masala', 'chickpea curry', 'punjabi chole', 'cooked chickpeas'],
    category: 'Legumes & Pulses',
    serving_size_g: 100,
    calories: 160,
    protein_g: 7.2,
    carbs_g: 22.0,
    fat_g: 5.0,
    fiber_g: 5.8,
    preparation: 'curry',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: P016'
  },

  // -------------------------------------------------------------
  // 5. PANEER & VEGETARIAN PROTEINS
  // -------------------------------------------------------------
  {
    id: 'ifct_paneer_raw',
    name: 'Raw Paneer / Indian Cottage Cheese',
    aliases: ['paneer', 'cottage cheese', 'raw paneer', 'fresh paneer', 'paneer cubes'],
    category: 'Dairy & Cheese',
    serving_size_g: 100,
    calories: 265,
    protein_g: 18.3,
    carbs_g: 3.4,
    fat_g: 20.8,
    fiber_g: 0.0,
    preparation: 'raw',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: D005'
  },
  {
    id: 'ifct_paneer_curry',
    name: 'Paneer Curry / Butter Masala',
    aliases: ['paneer curry', 'paneer butter masala', 'paneer tikka masala', 'palak paneer', 'shahi paneer', 'matar paneer', 'kadai paneer'],
    category: 'Indian Curries',
    serving_size_g: 100,
    calories: 210,
    protein_g: 11.5,
    carbs_g: 8.0,
    fat_g: 15.0,
    fiber_g: 1.5,
    preparation: 'curry',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: D008'
  },
  {
    id: 'usda_tofu_firm',
    name: 'Firm Tofu',
    aliases: ['tofu', 'firm tofu', 'soy tofu', 'steamed tofu', 'tofu cubes', 'grilled tofu', 'pan-seared tofu', 'pan seared tofu', 'seasoned tofu'],
    category: 'Plant Proteins',
    serving_size_g: 100,
    calories: 83,
    protein_g: 10.0,
    carbs_g: 2.1,
    fat_g: 5.3,
    fiber_g: 1.0,
    preparation: 'cooked',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 172448'
  },

  // -------------------------------------------------------------
  // 6. POULTRY, MEAT & BIRYANI
  // -------------------------------------------------------------
  {
    id: 'usda_chicken_breast_cooked',
    name: 'Cooked Chicken Breast',
    aliases: ['chicken', 'chicken breast', 'boiled chicken', 'cooked chicken breast', 'grilled chicken', 'baked chicken breast', 'steamed chicken'],
    category: 'Poultry & Meat',
    serving_size_g: 100,
    calories: 165,
    protein_g: 31.0,
    carbs_g: 0.0,
    fat_g: 3.6,
    fiber_g: 0.0,
    preparation: 'grilled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 171077'
  },
  {
    id: 'ifct_chicken_curry',
    name: 'Chicken Curry',
    aliases: ['chicken curry', 'indian chicken curry', 'chicken gravy', 'murgh curry'],
    category: 'Indian Curries',
    serving_size_g: 100,
    calories: 175,
    protein_g: 18.5,
    carbs_g: 4.2,
    fat_g: 9.5,
    fiber_g: 0.8,
    preparation: 'curry',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: M003'
  },
  {
    id: 'ifct_chicken_biryani',
    name: 'Chicken Biryani',
    aliases: ['chicken biryani', 'biryani', 'hyderabadi chicken biryani', 'dum biryani chicken'],
    category: 'Rice Specialties',
    serving_size_g: 100,
    calories: 180,
    protein_g: 11.2,
    carbs_g: 21.5,
    fat_g: 5.8,
    fiber_g: 1.2,
    preparation: 'cooked',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: M009'
  },
  {
    id: 'ifct_mutton_curry',
    name: 'Mutton Curry',
    aliases: ['mutton', 'mutton curry', 'goat curry', 'lamb curry', 'mutton gravy'],
    category: 'Poultry & Meat',
    serving_size_g: 100,
    calories: 215,
    protein_g: 17.5,
    carbs_g: 3.5,
    fat_g: 14.8,
    fiber_g: 0.5,
    preparation: 'curry',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: M014'
  },
  {
    id: 'usda_salmon_cooked',
    name: 'Grilled Salmon',
    aliases: ['salmon', 'grilled salmon', 'atlantic salmon', 'baked salmon'],
    category: 'Fish & Seafood',
    serving_size_g: 100,
    calories: 206,
    protein_g: 22.1,
    carbs_g: 0.0,
    fat_g: 12.3,
    fiber_g: 0.0,
    preparation: 'grilled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173686'
  },
  {
    id: 'ifct_fish_curry',
    name: 'Fish Curry',
    aliases: ['fish', 'fish curry', 'indian fish curry', 'meen curry', 'machli curry'],
    category: 'Fish & Seafood',
    serving_size_g: 100,
    calories: 140,
    protein_g: 16.0,
    carbs_g: 3.0,
    fat_g: 7.0,
    fiber_g: 0.6,
    preparation: 'curry',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: F005'
  },

  // -------------------------------------------------------------
  // 7. EGGS
  // -------------------------------------------------------------
  {
    id: 'usda_egg_boiled',
    name: 'Hard Boiled Egg',
    aliases: ['egg', 'boiled egg', 'hard boiled egg', 'soft boiled egg', 'egg white'],
    category: 'Eggs & Poultry',
    serving_size_g: 100,
    calories: 155,
    protein_g: 12.6,
    carbs_g: 1.1,
    fat_g: 10.6,
    fiber_g: 0.0,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173424'
  },
  {
    id: 'usda_egg_omelette',
    name: 'Egg Omelette',
    aliases: ['omelette', 'egg omelette', 'scrambled eggs', 'fried egg', 'masala omelette'],
    category: 'Eggs & Poultry',
    serving_size_g: 100,
    calories: 196,
    protein_g: 13.5,
    carbs_g: 2.0,
    fat_g: 15.0,
    fiber_g: 0.2,
    preparation: 'fried',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 171287'
  },

  // -------------------------------------------------------------
  // 8. DAIRY & CURD
  // -------------------------------------------------------------
  {
    id: 'ifct_curd_dahi',
    name: 'Curd / Plain Yogurt',
    aliases: ['curd', 'dahi', 'yogurt', 'plain yogurt', 'skyr', 'greek yogurt'],
    category: 'Dairy Products',
    serving_size_g: 100,
    calories: 61,
    protein_g: 3.5,
    carbs_g: 4.7,
    fat_g: 3.3,
    fiber_g: 0.0,
    preparation: 'raw',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: D001'
  },
  {
    id: 'usda_milk_whole',
    name: 'Cow Milk',
    aliases: ['milk', 'cow milk', 'whole milk', 'toned milk'],
    category: 'Dairy Products',
    serving_size_g: 100,
    calories: 61,
    protein_g: 3.2,
    carbs_g: 4.8,
    fat_g: 3.3,
    fiber_g: 0.0,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 171265'
  },

  // -------------------------------------------------------------
  // 9. VEGETABLES & SIDES
  // -------------------------------------------------------------
  {
    id: 'ifct_mixed_vegetables_curry',
    name: 'Cooked Mixed Vegetables',
    aliases: ['vegetables', 'mixed vegetables', 'veg sabzi', 'sabzi', 'steamed vegetables', 'sauteed vegetables', 'mixed veg'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 65,
    protein_g: 2.0,
    carbs_g: 8.5,
    fat_g: 2.5,
    fiber_g: 3.2,
    preparation: 'cooked',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: V001'
  },
  {
    id: 'usda_broccoli_steamed',
    name: 'Steamed Broccoli',
    aliases: ['broccoli', 'steamed broccoli', 'boiled broccoli'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 35,
    protein_g: 2.4,
    carbs_g: 7.2,
    fat_g: 0.4,
    fiber_g: 3.3,
    preparation: 'steamed',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169980'
  },
  {
    id: 'usda_potato_boiled',
    name: 'Boiled Potato',
    aliases: ['potato', 'boiled potato', 'mashed potato', 'steamed potato', 'aloo boiled'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 87,
    protein_g: 1.9,
    carbs_g: 20.1,
    fat_g: 0.1,
    fiber_g: 1.8,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170032'
  },
  {
    id: 'usda_potato_fried',
    name: 'Fried Potatoes / French Fries',
    aliases: ['fried potato', 'french fries', 'potato fry', 'deep fried potatoes', 'chips'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 312,
    protein_g: 3.4,
    carbs_g: 41.4,
    fat_g: 15.0,
    fiber_g: 3.8,
    preparation: 'deep_fried',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170093'
  },

  // -------------------------------------------------------------
  // 10. FRUITS
  // -------------------------------------------------------------
  {
    id: 'usda_banana_raw',
    name: 'Banana',
    aliases: ['banana', 'raw banana', 'fresh banana', 'kela'],
    category: 'Fruits',
    serving_size_g: 100,
    calories: 89,
    protein_g: 1.1,
    carbs_g: 22.8,
    fat_g: 0.3,
    fiber_g: 2.6,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173944'
  },
  {
    id: 'usda_apple_raw',
    name: 'Apple',
    aliases: ['apple', 'red apple', 'fresh apple', 'sliced apple', 'seb'],
    category: 'Fruits',
    serving_size_g: 100,
    calories: 52,
    protein_g: 0.3,
    carbs_g: 13.8,
    fat_g: 0.2,
    fiber_g: 2.4,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 171688'
  },
  {
    id: 'usda_orange_raw',
    name: 'Orange',
    aliases: ['orange', 'fresh orange', 'santra'],
    category: 'Fruits',
    serving_size_g: 100,
    calories: 47,
    protein_g: 0.9,
    carbs_g: 11.8,
    fat_g: 0.1,
    fiber_g: 2.4,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169097'
  },

  // -------------------------------------------------------------
  // 11. NUTS & HEALTHY FATS
  // -------------------------------------------------------------
  {
    id: 'usda_peanuts_raw',
    name: 'Peanuts',
    aliases: ['peanuts', 'roasted peanuts', 'groundnuts', 'moongphali'],
    category: 'Nuts & Seeds',
    serving_size_g: 100,
    calories: 567,
    protein_g: 25.8,
    carbs_g: 16.1,
    fat_g: 49.2,
    fiber_g: 8.5,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 172430'
  },
  {
    id: 'usda_peanut_butter',
    name: 'Peanut Butter',
    aliases: ['peanut butter', 'smooth peanut butter', 'crunchy peanut butter'],
    category: 'Nuts & Seeds',
    serving_size_g: 100,
    calories: 588,
    protein_g: 25.1,
    carbs_g: 20.0,
    fat_g: 50.4,
    fiber_g: 6.0,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 174266'
  },
  {
    id: 'usda_mixed_nuts',
    name: 'Almonds & Mixed Nuts',
    aliases: ['nuts', 'almonds', 'mixed nuts', 'cashews', 'walnuts', 'badam'],
    category: 'Nuts & Seeds',
    serving_size_g: 100,
    calories: 607,
    protein_g: 20.0,
    carbs_g: 21.0,
    fat_g: 54.0,
    fiber_g: 10.0,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170567'
  },

  // -------------------------------------------------------------
  // 10. GLOBAL MAINS, SALADS, FAST CASUAL & DESSERTS
  // -------------------------------------------------------------
  {
    id: 'usda_pizza_cheese',
    name: 'Cheese Pizza',
    aliases: ['pizza', 'cheese pizza', 'slice of pizza', 'baked pizza', 'veg pizza', 'margherita pizza'],
    category: 'Global Mains',
    serving_size_g: 100,
    calories: 266,
    protein_g: 11.4,
    carbs_g: 33.3,
    fat_g: 9.8,
    fiber_g: 2.3,
    preparation: 'baked',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173292'
  },
  {
    id: 'usda_burger',
    name: 'Burger',
    aliases: ['burger', 'hamburger', 'cheeseburger', 'veggie burger', 'patty burger', 'chicken burger'],
    category: 'Global Mains',
    serving_size_g: 100,
    calories: 254,
    protein_g: 13.3,
    carbs_g: 24.8,
    fat_g: 11.5,
    fiber_g: 1.5,
    preparation: 'grilled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173322'
  },
  {
    id: 'usda_garden_salad',
    name: 'Fresh Garden Salad',
    aliases: ['salad', 'garden salad', 'green salad', 'cucumber salad', 'mixed salad', 'fresh salad', 'side salad'],
    category: 'Vegetables & Salads',
    serving_size_g: 100,
    calories: 33,
    protein_g: 1.6,
    carbs_g: 6.2,
    fat_g: 0.2,
    fiber_g: 2.1,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170404'
  },
  {
    id: 'usda_fried_rice',
    name: 'Vegetable Fried Rice',
    aliases: ['fried rice', 'veg fried rice', 'vegetable fried rice', 'egg fried rice', 'stir fried rice'],
    category: 'Grains & Cereals',
    serving_size_g: 100,
    calories: 168,
    protein_g: 3.8,
    carbs_g: 31.2,
    fat_g: 3.2,
    fiber_g: 1.5,
    preparation: 'fried',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173216'
  },
  {
    id: 'usda_fruit_bowl',
    name: 'Fresh Fruit Bowl',
    aliases: ['fruit bowl', 'mixed fruits', 'fresh fruit salad', 'fruit plate', 'seasonal fruits', 'cut fruits', 'bowl of fruits'],
    category: 'Fruits',
    serving_size_g: 100,
    calories: 54,
    protein_g: 0.8,
    carbs_g: 13.8,
    fat_g: 0.2,
    fiber_g: 2.0,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 171708'
  },
  {
    id: 'in_paneer_butter_masala',
    name: 'Paneer Butter Masala',
    aliases: ['paneer butter masala', 'paneer makhani', 'shahi paneer', 'paneer tikka masala'],
    category: 'Curries & Dals',
    serving_size_g: 100,
    calories: 228,
    protein_g: 10.8,
    carbs_g: 7.5,
    fat_g: 18.2,
    fiber_g: 1.8,
    preparation: 'curry',
    source: 'IFCT / ICMR',
    source_id: 'IFCT-M-042'
  },
  {
    id: 'ifct_vegetable_raita',
    name: 'Vegetable Raita',
    aliases: ['raita', 'vegetable raita', 'cucumber raita', 'onion raita', 'boondi raita', 'dahi raita', 'curd raita'],
    category: 'Dairy & Accompaniments',
    serving_size_g: 100,
    calories: 62,
    protein_g: 3.1,
    carbs_g: 4.8,
    fat_g: 3.4,
    fiber_g: 0.6,
    preparation: 'raw',
    source: 'Indian Food Composition Tables (IFCT / ICMR)',
    source_id: 'IFCT: D007'
  },
  {
    id: 'usda_sweet_corn',
    name: 'Sweet Corn',
    aliases: ['corn', 'sweet corn', 'boiled corn', 'steamed corn', 'corn kernels', 'yellow corn'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 86,
    protein_g: 3.2,
    carbs_g: 19.0,
    fat_g: 1.2,
    fiber_g: 2.0,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169998'
  },
  {
    id: 'usda_cherry_tomatoes',
    name: 'Cherry Tomatoes',
    aliases: ['tomatoes', 'cherry tomatoes', 'tomato', 'sliced tomatoes', 'grape tomatoes', 'diced tomato'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 18,
    protein_g: 0.9,
    carbs_g: 3.9,
    fat_g: 0.2,
    fiber_g: 1.2,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170457'
  },
  {
    id: 'usda_cucumber',
    name: 'Cucumber',
    aliases: ['cucumber', 'cucumbers', 'sliced cucumber', 'diced cucumber', 'kheera'],
    category: 'Vegetables & Salads',
    serving_size_g: 100,
    calories: 15,
    protein_g: 0.7,
    carbs_g: 3.6,
    fat_g: 0.1,
    fiber_g: 0.5,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169225'
  },
  {
    id: 'usda_lettuce',
    name: 'Lettuce / Salad Greens',
    aliases: ['lettuce', 'salad greens', 'romaine lettuce', 'green lettuce', 'salad leaves', 'mixed greens'],
    category: 'Vegetables & Salads',
    serving_size_g: 100,
    calories: 15,
    protein_g: 1.4,
    carbs_g: 2.9,
    fat_g: 0.2,
    fiber_g: 1.3,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169248'
  },
  {
    id: 'usda_edamame',
    name: 'Edamame',
    aliases: ['edamame', 'soybeans', 'green soybeans', 'steamed edamame'],
    category: 'Plant Proteins',
    serving_size_g: 100,
    calories: 122,
    protein_g: 11.9,
    carbs_g: 8.9,
    fat_g: 5.2,
    fiber_g: 5.2,
    preparation: 'steamed',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 172441'
  },
  {
    id: 'usda_quail_eggs',
    name: 'Quail Eggs',
    aliases: ['quail eggs', 'quail egg', 'boiled quail eggs'],
    category: 'Eggs & Poultry',
    serving_size_g: 100,
    calories: 158,
    protein_g: 13.0,
    carbs_g: 0.4,
    fat_g: 11.1,
    fiber_g: 0.0,
    preparation: 'boiled',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 173426'
  },
  {
    id: 'usda_red_cabbage',
    name: 'Red / Purple Cabbage',
    aliases: ['red cabbage', 'purple cabbage', 'shredded cabbage', 'cabbage'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 31,
    protein_g: 1.4,
    carbs_g: 7.4,
    fat_g: 0.2,
    fiber_g: 2.1,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 169976'
  },
  {
    id: 'usda_scallions',
    name: 'Scallions / Spring Onions',
    aliases: ['scallions', 'spring onions', 'green onions', 'spring onion'],
    category: 'Vegetables & Salads',
    serving_size_g: 100,
    calories: 32,
    protein_g: 1.8,
    carbs_g: 7.3,
    fat_g: 0.2,
    fiber_g: 2.6,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170002'
  },
  {
    id: 'usda_spinach',
    name: 'Spinach',
    aliases: ['spinach', 'cooked spinach', 'palak', 'baby spinach', 'steamed spinach'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 23,
    protein_g: 2.9,
    carbs_g: 3.6,
    fat_g: 0.4,
    fiber_g: 2.2,
    preparation: 'cooked',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 168462'
  },
  {
    id: 'usda_carrots',
    name: 'Carrot',
    aliases: ['carrot', 'carrots', 'sliced carrots', 'diced carrots', 'gajar'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 41,
    protein_g: 0.9,
    carbs_g: 9.6,
    fat_g: 0.2,
    fiber_g: 2.8,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170393'
  },
  {
    id: 'usda_bell_pepper',
    name: 'Bell Pepper / Capsicum',
    aliases: ['bell pepper', 'capsicum', 'sweet pepper', 'green pepper', 'red pepper'],
    category: 'Vegetables',
    serving_size_g: 100,
    calories: 26,
    protein_g: 1.0,
    carbs_g: 6.0,
    fat_g: 0.3,
    fiber_g: 2.1,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 170427'
  },
  {
    id: 'usda_water',
    name: 'Water',
    aliases: ['water', 'glass of water', 'drinking water', 'plain water'],
    category: 'Beverage',
    serving_size_g: 100,
    calories: 0,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 0,
    fiber_g: 0,
    preparation: 'raw',
    source: 'USDA FoodData Central',
    source_id: 'FDC ID: 171695'
  }
];

module.exports = {
  NUTRITION_DATABASE
};
